### ISSUE TITLE
Bundle structured to support extensions like FHIR does

### ISSUE THREAD

**Issue by carlyh-micb** [the-human-colossus-foundation/oca-spec#53] opened 2024-03-06 20:41 UTC
Adding extensions to OCA?

I remember reading how FHIR really benefited from supporting extensions to the specification depending on the ecosystem. I also see the addition of presentation/collection being added as a different chunk to the OCA Bundle.

What if a bundle were structured:

{
{OCA core SAID and core overlays},
{OCA presentation/collection SAID and overlays},
{OCA extensions SAID and extension overlays}
}

In this way, SAIDs could be preserved for different 'chunks' and extensions could be included by others adopting the specification.

We could even standardize that extensions are given a name (some specific metadata, variables that all extensions must provide) and could be standardized by other groups in different ecosystems?

**Comment by carlyh-micb** [comment] 2024-03-07 16:29
FHIR supports extensions to their core specification: https://www.hl7.org/fhir/extensibility.html

**Comment by mitfik** [comment] 2024-03-08 14:36
I think you need to provide specific example to better understand the need but on high level  OCA is by definition created in a way that you can extend it, there is no need to change anything in the spec or bundle. "Our" extensions are overlays they providing specific functionality into the stack. Some of the comes with the bundle some of them are applied by the user himself (e.g. sensitivity overlay)

**Comment by mitfik** [comment] 2024-03-12 20:57
Structure of the presentation can be found in oca-presentation repo, specifically here few example for testing: https://github.com/THCLab/oca-presentation/tree/main/presentation-base/tests/presentation_examples

Regarding OCA bundle the best source is OCA-RS, specifically test: https://github.com/THCLab/oca-rs/blob/main/oca-bundle/tests/create_oca_test.rs

**Comment by carlyh-micb** [comment] 2024-03-13 15:18
From the code I can't tell what is correct.

{
"bundles": {
...
},
"dependencies": []
}
The JSON from Excel Template -> JSON of https://oca.colossi.network/ecosystem/oca-parser.html will return in the form of:
{
"schema": [
...
]
}

And how does presentations fit into this syntax?

If the OCA Bundle is the capture base and official overlays, and then we add presentation information to another section, plus add an extensions section, this collection could be called an OCA Package.

I also note that one possible syntax calls is "bundles", does this imply there can be more than one OCA Bundle (and thus multiple capture bases) within an OCA Package?

**Comment by carlyh-micb** [comment] 2024-03-15 20:31
What about something like this:

(code of overlays is not consistent, I have copied them from other use cases like a lorum ipsum)

An OCA package would consist of the core schema (in section "schema") and extensions are added after this core which can be within over governance domains.

As FHIR describes "It is common for specific implementations to have valid requirements that are not part of these agreed common requirements."

The common requirements would go in schema, the extensions would go after. All collected together they would create an OCA package.

In this example, there is a capture base for the schema. Then an extension called presentation which itself has two overlays in the OCA package. Then there is a second extension called "research" which has another two overlays (two language variants of an example overlay).

```
{
  "schema": {
    "type": "spec/capture_base/1.0",
    "digest": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
    "classification": "RDF106",
    "attributes": {
      "Albumin_concentration": "Numeric",
      "Glucose_concentration": "Numeric",
      "Sample _name": "Text",
      "Sample_type": "Text"
    },
    "flagged_attributes": []
  },
  "Extensions": {
    "Presentation": {
      "extension_documentation": "https://github.com/the-human-colossus-foundation/extension-presentation/",
      "overlays": {
        "presentation_base": {
          "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
          "digest": "XXXX",
          "type": "spec/overlays/unit_framing/1.0",
          "Framing_metadata": {
            "frame_id": "UCUM",
            "frame_label": "",
            "frame_location": "https://ucum.org/",
            "frame_version": ""
          },
          "unit_framing": {
            "mg/dL": {
              "Term_id": "mg/dL",
              "Predicate_id": "skos:exactMatch",
              "Framing_justification": "semapv:ManualMappingCuration"
            }
          }
        }
      }
    },
    "Research": {
      "extension_documentation": "https://github.com/agrifooddatacanada/extension-research",
      "overlays": {
        "example": [
          {
            "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
            "digest": "XXXX",
            "type": "spec/overlays/example/1.0",
            "language": "en-CA",
            "examples": {
              "Albumin_concentration": "52.69",
              "Glucose_concentration": "8.7",
              "Sample _name": "Carlys_sample",
              "Sample_type": "BLD003"
            }
          },
          {
            "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
            "digest": "XXXX",
            "type": "spec/overlays/example/1.0",
            "language": "ar",
            "examples": {
              "Albumin_concentration": "52.69",
              "Glucose_concentration": "8.7",
              "Sample _name": "عينة",
              "Sample_type": "BLD003"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by carlyh-micb** [comment] 2024-03-19 20:14
The challenge to this is that any parser written for OCA would pick and choose which extensions to support.

This may also change the underlying AST model of the schema and may present a challenge for interoperability? Within the AST model could there be partitions? Core Bundle, and each extension its own object?

Could OCA (core and each extension) have a syntax for a config file? Each time OCA Core is updated to a new version it would be expressed in a config file that the parser could ingest to make it a bit easier to update any parser? By the same token any extension could also be expressed in the same config file syntax for parser ingestion.

**Comment by blelump** [comment] 2024-08-02 16:47
It is the topic to be addressed within ORFG, specifically to ensure the final group recommendation covers it. The `extension` construct proposed above, when flattened, ends up as the list of overlays. Therefore, it is the topic of the so-called `community overlays.`

**Comment by carlyh-micb** [comment] 2024-09-12 14:45
![image](https://github.com/user-attachments/assets/e4079fcf-16c8-4ca2-8198-237b880d3de3)

Since we need this feature to move forward, we've started work on adding overlays to the OCA schema bundle.
This is our proposed architecture for the JSON schema package object. OCA Schema bundle is preserved according to the standard, we will be adding extensions to hold overlays that we develop and also we needed a spot to put HCF presentation overlay so we added it as another extension.

Any thoughts? Anyone else creating their own overlays? Any recommendations on better syntax?

**Comment by carlyh-micb** [comment] 2024-09-12 15:00
If you have anything to share, even if it is half formed, an example of a complete new schema syntax as I have put above we can adopt and adapt to fit. We are in the early build stage right now so it is easy to change right now.

Here is the complete bundle syntax right now:

```
{
  "OCA_bundle": {
  "bundle": {
    "v": "OCAM10JSON000fcb_",
    "d": "EF2W3pw8gV8S8N0Bgde7H9o9Pw5TQFrkmXNZfUZMZ960",
    "capture_base": {
      "d": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
      "type": "spec/capture_base/1.0",
      "classification": "RDF107",
      "attributes": {
        "v1": "Numeric",
        "v2": "Text",
        "v3": [
          "Numeric"
        ],
        "v4": [
          "Text"
        ]
      },
      "flagged_attributes": []
    },
    "overlays": {
      "character_encoding": {
        "d": "EDow1-Cg8DT4ZhPYQLOFgWjsxK9t19l2dTcWljEdHpvT",
        "type": "spec/overlays/character_encoding/1.0",
        "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
        "attribute_character_encoding": {
          "v1": "utf-8",
          "v2": "utf-8",
          "v3": "utf-8",
          "v4": "utf-8"
        }
      },
      "format": {
        "d": "EDCZ9XKU6388PqVs5a8NUfZmSAI1ryYbi6bt35K7jQsf",
        "type": "spec/overlays/format/1.0",
        "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
        "attribute_formats": {
          "v1": "^[-+]?\\d*\\.?\\d+$",
          "v2": "^.{0,50}$",
          "v3": "^[-+]?\\d*\\.?\\d+$",
          "v4": "^.{0,50}$"
        }
      },
      "meta": [
        {
          "d": "EJwvjPmBY_7jm01tEgsDNoZD3LM0asDBksXu7q4bQ7_r",
          "language": "eng",
          "type": "spec/overlays/meta/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "description": "Schema example for testing overlays and extensions and presentation overlays.",
          "name": "Testing schema"
        },
        {
          "d": "EHy7czqzbX4mtZZVDqG8vmSixEw8FjeFIFu1fH2qKFp2",
          "language": "fra",
          "type": "spec/overlays/meta/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "description": "Exemple de schéma pour tester les superpositions, les extensions et les superpositions de présentation.",
          "name": "Schéma de test"
        }
      ],
      "label": [
        {
          "d": "ENVWgsOUCM1SswVDwqaf6pSuXo1i5bmIBgrNcdaN_MUn",
          "language": "eng",
          "type": "spec/overlays/label/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_labels": {
            "v1": "volume",
            "v2": "favourite colour",
            "v3": "weight",
            "v4": "samplers"
          },
          "attribute_categories": [],
          "category_labels": {}
        },
        {
          "d": "EOaijAuFrFllwc3vosz37t8hTUWf2DyJzMrmQjwid8JX",
          "language": "fra",
          "type": "spec/overlays/label/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_labels": {
            "v1": "volume",
            "v2": "Couleur préférée",
            "v3": "poids",
            "v4": "échantillonneuses(eurs)"
          },
          "attribute_categories": [],
          "category_labels": {}
        }
      ],
      "information": [
        {
          "d": "EAxVm_72VJ-aUIYkHYMFIyVqKQrVFVkNWgXaSaGGJV5E",
          "language": "eng",
          "type": "spec/overlays/information/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_information": {
            "v1": "Volume of water added to the sample.",
            "v2": "The users favourite colour",
            "v3": "weights of samples measured",
            "v4": "names of the people who sampled"
          }
        },
        {
          "d": "EPGiaKmt3kPb6X4ipi2bryi34wnJ_hkSlixvv0ZGrC_J",
          "language": "fra",
          "type": "spec/overlays/information/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_information": {
            "v1": "Volume d'eau ajouté à l'échantillon.",
            "v2": "La couleur préférée des utilisateurs",
            "v3": "poids des échantillons mesurés",
            "v4": "noms des personnes qui ont été échantillonnées"
          }
        }
      ],
      "conformance": {
        "d": "EE6KmDANs17wzX559CvFLqpkHvFqYoeWeOVi1I_cBD2r",
        "type": "spec/overlays/conformance/1.0",
        "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
        "attribute_conformance": {
          "v1": "O",
          "v2": "O",
          "v3": "M",
          "v4": "O"
        }
      },
      "entry_code": {
        "d": "EDbwMa32lyu1_kBn4n2uOXltpwtS4AFYDjv92xl9T2oz",
        "type": "spec/overlays/entry_code/1.0",
        "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
        "attribute_entry_codes": {
          "v2": [
            "001",
            "002",
            "003",
            "004",
            "005"
          ]
        }
      },
      "entry": [
        {
          "d": "EPIIohkNYHHNxLtpT1EtFX72wNsLk-f2R-8A0r6NvIOZ",
          "language": "eng",
          "type": "spec/overlays/entry/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_entries": {
            "v2": {
              "001": "Red",
              "002": "Green",
              "003": "Blue",
              "004": "Yellow",
              "005": "Orange"
            }
          }
        },
        {
          "d": "EJtn_65WzGX8DmufmHbc4cIY_F2LG2eFCUIT1IdOtnvE",
          "language": "fra",
          "type": "spec/overlays/entry/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_entries": {
            "v2": {
              "001": "Rouge",
              "002": "Vert",
              "003": "Bleu",
              "004": "Jaune",
              "005": "Orange"
            }
          }
        }
      ],
      "cardinality": {
        "d": "EP6EIJb24EYGvz1rgZQODjW-MqsoxlbvI6hmDFRDhPUO",
        "type": "spec/overlays/cardinality/1.0",
        "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
        "attribute_cardinality": {
          "v3": "1-5",
          "v4": "-10"
        }
      }
    }
  },
  "dependencies": []
},
  "Extensions": {
    "Presentation": {
      "extension_documentation": "https://github.com/the-human-colossus-foundation/extension-presentation/",
      "overlays": {
  "presentation": {
    "v": "1.0.0",
    "bd": "XXXdigestofthepreseentationbundle_ordigestofschemabundle?XX",
    "l": [
      "eng",
      "fra"
    ],
    "d": "notsurewhatthisis",
    "p": [
      {
        "ns": "",
        "ao": [
          "v2",
          "v1",
          "v4",
          "v3"
        ]
      }
    ],
    "po": [],
    "pl": {},
    "i": []
  }
}
    },
    "Research": {
      "extension_documentation": "https://github.com/agrifooddatacanada/extension-research",
      "overlays": {
        "example": [
          {
            "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
            "digest": "XXXX",
            "type": "extension/research/overlays/example/1.0",
            "language": "eng",
            "examples": {
              "v1": "12.3",
              "v2": "001",
              "v3": "2.3,3.3,5.6",
              "v4": "Jill;Fred;Wendy"
            }
          },
          {
            "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
            "digest": "XXXX",
            "type": "extension/research/overlays/example/1.0",
            "language": "fra",
            "examples": {
              "v1": "12.3",
              "v2": "001",
              "v3": "2.3,3.3,5.6",
              "v4": "Jill;Fred;Wendy"
            }
          }
        ],
        "separator": {
          "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
          "digest": "XXXX",
          "type": "extension/research/overlays/separator/1.0",
          "dataset_separators": {
            "dataset_delimiter": ",",
            "dataset_escape": "\\"
          },
          "attribute_separators": [
            {
              "v3": {
                "delimiter": ",",
                "escape": "\\"
              },
              "v4": {
                "delimiter": ";",
                "escape": ""
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by carlyh-micb** [comment] 2024-09-12 15:59
For my use case it is absolutely required for everything related to a schema be in a single .json file and pull it all together in a single JSON object.

{
bundle: ...
extensions: ...
presentation: ...
}

**Comment by carlyh-micb** [comment] 2024-09-12 16:59
![image](https://github.com/user-attachments/assets/07dce65b-6ad2-4d50-810e-5de31acbab60)

This is an updated version of the structure.

**Comment by carlyh-micb** [comment] 2024-09-24 13:21
ADC's current proposal for incorporating Extensions and Presentation overlays together with OCA-core.

```
{
  "oca_package": {
    "v:": "1.0.0",
    "d": "XXoca-package said place holderXX",
    "bundle": {
      "v": "OCAM10JSON000fcb_",
      "d": "EF2W3pw8gV8S8N0Bgde7H9o9Pw5TQFrkmXNZfUZMZ960",
      "capture_base": {
        "d": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
        "type": "spec/capture_base/1.0",
        "classification": "RDF107",
        "attributes": {
          "v1": "Numeric",
          "v2": "Text",
          "v3": [
            "Numeric"
          ],
          "v4": [
            "Text"
          ]
        },
        "flagged_attributes": []
      },
      "overlays": {
        "character_encoding": {
          "d": "EDow1-Cg8DT4ZhPYQLOFgWjsxK9t19l2dTcWljEdHpvT",
          "type": "spec/overlays/character_encoding/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_character_encoding": {
            "v1": "utf-8",
            "v2": "utf-8",
            "v3": "utf-8",
            "v4": "utf-8"
          }
        },
        "format": {
          "d": "EDCZ9XKU6388PqVs5a8NUfZmSAI1ryYbi6bt35K7jQsf",
          "type": "spec/overlays/format/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_formats": {
            "v1": "^[-+]?\\d*\\.?\\d+$",
            "v2": "^.{0,50}$",
            "v3": "^[-+]?\\d*\\.?\\d+$",
            "v4": "^.{0,50}$"
          }
        },
        "meta": [
          {
            "d": "EJwvjPmBY_7jm01tEgsDNoZD3LM0asDBksXu7q4bQ7_r",
            "language": "eng",
            "type": "spec/overlays/meta/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "description": "Schema example for testing overlays and extensions and presentation overlays.",
            "name": "Testing schema"
          },
          {
            "d": "EHy7czqzbX4mtZZVDqG8vmSixEw8FjeFIFu1fH2qKFp2",
            "language": "fra",
            "type": "spec/overlays/meta/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "description": "Exemple de schéma pour tester les superpositions, les extensions et les superpositions de présentation.",
            "name": "Schéma de test"
          }
        ],
        "label": [
          {
            "d": "ENVWgsOUCM1SswVDwqaf6pSuXo1i5bmIBgrNcdaN_MUn",
            "language": "eng",
            "type": "spec/overlays/label/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "attribute_labels": {
              "v1": "volume",
              "v2": "favourite colour",
              "v3": "weight",
              "v4": "samplers"
            },
            "attribute_categories": [],
            "category_labels": {}
          },
          {
            "d": "EOaijAuFrFllwc3vosz37t8hTUWf2DyJzMrmQjwid8JX",
            "language": "fra",
            "type": "spec/overlays/label/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "attribute_labels": {
              "v1": "volume",
              "v2": "Couleur préférée",
              "v3": "poids",
              "v4": "échantillonneuses(eurs)"
            },
            "attribute_categories": [],
            "category_labels": {}
          }
        ],
        "information": [
          {
            "d": "EAxVm_72VJ-aUIYkHYMFIyVqKQrVFVkNWgXaSaGGJV5E",
            "language": "eng",
            "type": "spec/overlays/information/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "attribute_information": {
              "v1": "Volume of water added to the sample.",
              "v2": "The users favourite colour",
              "v3": "weights of samples measured",
              "v4": "names of the people who sampled"
            }
          },
          {
            "d": "EPGiaKmt3kPb6X4ipi2bryi34wnJ_hkSlixvv0ZGrC_J",
            "language": "fra",
            "type": "spec/overlays/information/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "attribute_information": {
              "v1": "Volume d'eau ajouté à l'échantillon.",
              "v2": "La couleur préférée des utilisateurs",
              "v3": "poids des échantillons mesurés",
              "v4": "noms des personnes qui ont été échantillonnées"
            }
          }
        ],
        "conformance": {
          "d": "EE6KmDANs17wzX559CvFLqpkHvFqYoeWeOVi1I_cBD2r",
          "type": "spec/overlays/conformance/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_conformance": {
            "v1": "O",
            "v2": "O",
            "v3": "M",
            "v4": "O"
          }
        },
        "entry_code": {
          "d": "EDbwMa32lyu1_kBn4n2uOXltpwtS4AFYDjv92xl9T2oz",
          "type": "spec/overlays/entry_code/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_entry_codes": {
            "v2": [
              "001",
              "002",
              "003",
              "004",
              "005"
            ]
          }
        },
        "entry": [
          {
            "d": "EPIIohkNYHHNxLtpT1EtFX72wNsLk-f2R-8A0r6NvIOZ",
            "language": "eng",
            "type": "spec/overlays/entry/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "attribute_entries": {
              "v2": {
                "001": "Red",
                "002": "Green",
                "003": "Blue",
                "004": "Yellow",
                "005": "Orange"
              }
            }
          },
          {
            "d": "EJtn_65WzGX8DmufmHbc4cIY_F2LG2eFCUIT1IdOtnvE",
            "language": "fra",
            "type": "spec/overlays/entry/1.0",
            "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
            "attribute_entries": {
              "v2": {
                "001": "Rouge",
                "002": "Vert",
                "003": "Bleu",
                "004": "Jaune",
                "005": "Orange"
              }
            }
          }
        ],
        "cardinality": {
          "d": "EP6EIJb24EYGvz1rgZQODjW-MqsoxlbvI6hmDFRDhPUO",
          "type": "spec/overlays/cardinality/1.0",
          "capture_base": "EINdG1yMgVB3KcSzkqGNbpv2qs0hKwzSg2AWAGAQbbx0",
          "attribute_cardinality": {
            "v3": "1-5",
            "v4": "-10"
          }
        }
      }
    },
    "dependencies": [],
    "presentation": {
      "v": "1.0.0",
      "bd": "XXXdigestofthepreseentationbundle_ordigestofschemabundle?XX",
      "l": [
        "eng",
        "fra"
      ],
      "d": "notsurewhatthisis",
      "p": [
        {
          "ns": "",
          "ao": [
            "v2",
            "v1",
            "v4",
            "v3"
          ]
        }
      ],
      "po": [],
      "pl": {},
      "i": []
    },
    "extensions": [
      {
        "separator": {
          "d": "XXXX",
          "type": "adc/overlays/separator/1.0",
          "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
          "dataset_separator": {
            "delimiter": ",",
            "escape": "\\"
          },
          "attribute_separators": {
            "v3": {
              "delimiter": ",",
              "escape": "\\"
            },
            "v4": {
              "delimiter": ";",
              "escape": ""
            }
          }
        }
      },
      {
        "example": [
          {
            "d": "XXXX",
            "language": "eng",
            "type": "adc/overlays/example/1.0",
            "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
            "attribute_examples": [
              {
                "v1": [
                  "12.3",
                  "13.3",
                  "14.6"
                ],
                "v2": [
                  "001"
                ],
                "v3": [
                  "2.3,3.3,5.6"
                ],
                "v4": [
                  "Jill;Fred;Wendy"
                ]
              }
            ]
          },
          {
            "d": "XXXX",
            "language": "fra",
            "type": "adc/overlays/example/1.0",
            "capture_base": "Etszl9LgLUjllI950rd2lO6rF5-BP_jGzXGBPkFZCZFA",
            "attribute_examples": [
              {
                "v1": [
                  "12.3"
                ],
                "v2": [
                  "001"
                ],
                "v3": [
                  "2.3,3.3,5.6"
                ],
                "v4": [
                  "Jill;Fred;Wendy"
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}

A picture that summarizes. The highlighted objects are all at the same 'level' in the OCA Package. There are no hierarchies of extensions - all community overlays are added overlay by overlay and the type can specify what communities are developing the different overlays.
![image](https://github.com/user-attachments/assets/a4209b0b-497f-47e2-8565-b91c4a307140)

```

**Comment by mitfik** [comment] 2024-10-20 20:54
Duplicate of #68

**Closed by mitfik** 2024-10-20 20:54 UTC
